# Generated by Django 6.1 on 2026-08-31 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id_prioridad', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.DecimalField(decimal_places=0, max_digits=2)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'prioridad',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id_perfil', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=20)),
                ('idioma', models.CharField(max_length=40)),
                ('interfaz', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('solucion', models.CharField(blank=True, max_length=2000, null=True)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.categoria')),
                ('id_estado', models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.estado')),
                ('id_prioridad', models.ForeignKey(blank=True, db_column='id_prioridad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.prioridad')),
                ('id_tecnico', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='ClasificacionIA',
            fields=[
                ('id_clasificacion_ia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=100)),
                ('nivel_confianza', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_clasificacion', models.DateTimeField(blank=True, null=True)),
                ('modelo_utilizado', models.CharField(max_length=100)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones_ia', to='tickets.categoria')),
                ('id_prioridad', models.ForeignKey(db_column='id_prioridad', on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones_ia', to='tickets.prioridad')),
                ('id_ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_ia', to='tickets.ticket')),
            ],
            options={
                'db_table': 'clasificacion_ia',
            },
        ),
    ]
