# Generated by Django 6.1 on 2026-10-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_especialidadtecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='tema',
        ),
        migrations.AddField(
            model_name='settings',
            name='alertas_criticas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='alertas_estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='asignacion_automatica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='dos_factores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='dos_factores_obligatorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='notif_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='resumen_diario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='resumen_semanal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='sugerencias_respuesta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='umbral_ia',
            field=models.PositiveIntegerField(default=85),
        ),
        migrations.AlterField(
            model_name='settings',
            name='idioma',
            field=models.CharField(default='Español', max_length=40),
        ),
        migrations.AlterField(
            model_name='settings',
            name='interfaz',
            field=models.CharField(default='Cómoda', max_length=100),
        ),
    ]
