# Generated by Django 6.1 on 2026-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_settings_tema_settings_alertas_criticas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasificacionia',
            old_name='nivel_confianza',
            new_name='nivel_confianza_categoria',
        ),
        migrations.AddField(
            model_name='clasificacionia',
            name='nivel_confianza_prioridad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
