# Generated by Django 6.1 on 2026-10-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_nivel_confianza_clasificacionia_nivel_confianza_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='dark_mode',
            new_name='tema',
        ),
    ]
