# Generated by Django 6.1 on 2026-08-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria_predicha', models.CharField(blank=True, max_length=50, null=True)),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('categoria_corregida', models.CharField(blank=True, choices=[('Accesos', 'Accesos'), ('Hardware', 'Hardware'), ('Software', 'Software'), ('Red', 'Red'), ('Seguridad', 'Seguridad'), ('Consulta general', 'Consulta general')], max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
