# Generated by Django 6.1 on 2026-08-31 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos_especializados', to='tickets.categoria')),
                ('tecnico', models.ForeignKey(limit_choices_to={'groups__name': 'Tecnico'}, on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'especialidad_tecnico',
                'unique_together': {('tecnico', 'categoria')},
            },
        ),
    ]
