# Generated by Django 6.1 on 2026-08-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
